use_frameworks!

platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
source 'https://github.com/openNYcc/NYSpec.git'
target 'GCB_UserLib_Example' do
  pod 'GCB_UserLib', :path => '../'
  target 'GCB_UserLib_Tests' do
    inherit! :search_paths

    
  end
end
